apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.profilesApi.name }}
  labels:
    app:  {{ .Values.profilesApi.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.profilesApi.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app:  {{ .Values.profilesApi.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
      - name:  {{ .Values.profilesApi.name }}
        image:  {{ .Values.image.repository }}:{{ .Values.image.tag }}-{{ .Values.profilesApi.name }}
        args:
          - "--config=/app/config/app.yml"
          - "--sentry-config=/app/config/sentry.yml"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.profilesApi.resources | indent 10 }}
        livenessProbe:
{{ toYaml .Values.profilesApi.livenessProbe | indent 10 }}
        readinessProbe:
{{ toYaml .Values.profilesApi.readinessProbe | indent 10 }}
        ports:
        - containerPort:  {{ .Values.service.internalPort }}
          name:  {{ .Values.profilesApi.name }}
        - containerPort:  {{ .Values.profilesApi.metrics.port }}
          name:  {{ .Values.profilesApi.metrics.portName }}
        volumeMounts:
          - name: config
            mountPath: /app/config/
            readOnly: true
      volumes:
        - name: config
          secret:
            secretName: profile-config

      restartPolicy: Always
