version: '3.9'
services:
  db:
    image: postgres:15
    hostname: pg
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U test
      interval: 3s
      timeout: 3s
      retries: 3

  init-db:
    image: postgres:15
    command: /init/initdb.sh
    volumes:
      - ../migration:/init
    depends_on:
      db:
        condition: service_healthy

  gateway:
    image: nginx:1.23.3
    volumes:
      - ../files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    extra_hosts:
    - "host.docker.internal:host-gateway"
