### get user 1
GET http://localhost:8000/user/petrov

### get user 2
GET http://localhost:8000/user/ivanov

### delete user 1
DELETE http://localhost:8000/user/petrov

### delete user 2>
DELETE http://localhost:8000/user/ivanov

### add new user 1
POST http://localhost:8000/user
Content-Type: application/json

{
    "username": "petrov",
    "firstname": "Alex",
    "lastname": "Petrov",
    "email": "a.petrov@xmail.com",
    "phone": "123"
}

### add new user 2
POST http://localhost:8000/user
Content-Type: application/json

{
    "username": "ivanov",
    "firstname": "Andrey",
    "lastname": "Ivanov",
    "email": "a.ivanov@xmail.com",
    "phone": "456"
}

### update user 1
PUT http://localhost:8000/user/petrov
Content-Type: application/json

{
    "firstname": "Alex",
    "lastname": "Petrov",
    "email": "a.petrov@zzxz.com",
    "phone": "789"
}

### healthcheck
GET http://localhost:8000/health

### liveness
GET http://localhost:8000/liveness

### readness
GET http://localhost:8000/readness

