@startuml

actor User
rectangle NginxIngress
rectangle Auth
rectangle App
rectangle Database

User->NginxIngress
NginxIngress-->Auth: login\nlogout
Auth<-->NginxIngress: check user\nsession
NginxIngress-->App: create new user\nor with permissions\nget,update,delete user  
App-->Database: create new user\n get, update, delete
Auth<-->Database: check user password

@enduml
